const initialItems = [
  {
    name: 'AArch64',
    componentName: 'Aarch64Plain',
    fileName: 'aarch64-plain',
    key: ['ARM64', 'ARM', '64-bit'],
  },
  {
    name: 'AdonisJS',
    componentName: 'AdonisjsOriginalWordmark',
    fileName: 'adonisjs-original-wordmark',
    key: [
      'BPM',
      'Business Process Management',
      'SOPs',
      'Standard Operating Procedures',
      'framework',
    ],
  },
  {
    name: 'After Effects',
    componentName: 'AftereffectsPlain',
    fileName: 'aftereffects-plain',
    key: ['adobe', 'adobe after effects'],
  },
  {
    name: 'AWS',
    componentName: 'AmazonwebservicesPlainWordmark',
    fileName: 'amazonwebservices-plain-wordmark',
    key: ['Amazon Web Services'],
  },
  {
    name: 'Android',
    componentName: 'AndroidPlain',
    fileName: 'android-plain',
    key: ['os', 'android'],
  },
  {
    name: 'AngularJS',
    componentName: 'AngularjsPlain',
    fileName: 'angularjs-plain',
    key: [],
  },
  {
    name: 'Apache',
    componentName: 'ApachePlain',
    fileName: 'apache-plain',
    key: [],
  },
  {
    name: 'Apachekafka',
    componentName: 'ApachekafkaOriginal',
    fileName: 'apachekafka-original',
    key: [],
  },
  {
    name: 'Appcelerator',
    componentName: 'AppceleratorOriginal',
    fileName: 'appcelerator-original',
    key: [],
  },
  {
    name: 'apple',
    componentName: 'AppleOriginal',
    fileName: 'apple-original',
    key: [],
  },
  {
    name: 'appwrite',
    componentName: 'AppwritePlain',
    fileName: 'appwrite-plain',
    key: [],
  },
  {
    name: 'arduino',
    componentName: 'ArduinoPlain',
    fileName: 'arduino-plain',
    key: [],
  },
  {
    name: 'atom',
    componentName: 'AtomOriginal',
    fileName: 'atom-original',
    key: [],
  },
  {
    name: 'azure',
    componentName: 'AzurePlain',
    fileName: 'azure-plain',
    key: [],
  },
  {
    name: 'babel',
    componentName: 'BabelPlain',
    fileName: 'babel-plain',
    key: [],
  },
  {
    name: 'backbonejs',
    componentName: 'BackbonejsPlain',
    fileName: 'backbonejs-plain',
    key: [],
  },
  {
    name: 'bash',
    componentName: 'BashPlain',
    fileName: 'bash-plain',
    key: [],
  },
  {
    name: 'behance',
    componentName: 'BehancePlain',
    fileName: 'behance-plain',
    key: [],
  },
  {
    name: 'Bitbucket',
    componentName: 'BitbucketOriginal',
    fileName: 'bitbucket-original',
    key: [],
  },
  {
    name: 'bootstrap',
    componentName: 'BootstrapPlain',
    fileName: 'bootstrap-plain',
    key: [],
  },
  {
    name: 'bower',
    componentName: 'BowerPlain',
    fileName: 'bower-plain',
    key: [],
  },
  {
    name: 'Bulma',
    componentName: 'BulmaPlain',
    fileName: 'bulma-plain',
    key: [],
  },
  {
    name: 'C',
    componentName: 'CPlain',
    fileName: 'c-plain',
    key: [],
  },
  {
    name: 'cakephp',
    componentName: 'CakephpPlain',
    fileName: 'cakephp-plain',
    key: [],
  },
  {
    name: 'canva',
    componentName: 'CanvaOriginal',
    fileName: 'canva-original',
    key: [],
  },
  {
    name: 'centos',
    componentName: 'CentosPlain',
    fileName: 'centos-plain',
    key: [],
  },
  {
    name: 'ceylon',
    componentName: 'CeylonPlain',
    fileName: 'ceylon-plain',
    key: [],
  },
  {
    name: 'chrome',
    componentName: 'ChromePlain',
    fileName: 'chrome-plain',
    key: [],
  },
  {
    name: 'circleci',
    componentName: 'CircleciPlain',
    fileName: 'circleci-plain',
    key: [],
  },
  {
    name: 'clojure',
    componentName: 'ClojureLine',
    fileName: 'clojure-line',
    key: [],
  },
  {
    name: 'clojurescript',
    componentName: 'ClojurescriptPlain',
    fileName: 'clojurescript-plain',
    key: [],
  },
  {
    name: 'codecov',
    componentName: 'CodecovPlain',
    fileName: 'codecov-plain',
    key: [],
  },
  {
    name: 'codeigniter',
    componentName: 'CodeigniterPlain',
    fileName: 'codeigniter-plain',
    key: [],
  },
  {
    name: 'codepen',
    componentName: 'CodepenPlain',
    fileName: 'codepen-plain',
    key: [],
  },
  {
    name: 'coffeescript',
    componentName: 'CoffeescriptOriginal',
    fileName: 'coffeescript-original',
    key: [],
  },
  {
    name: 'composer',
    componentName: 'ComposerLine',
    fileName: 'composer-line',
    key: [],
  },
  {
    name: 'confluence',
    componentName: 'ConfluenceOriginal',
    fileName: 'confluence-original',
    key: [],
  },
  {
    name: 'couchdb',
    componentName: 'CouchdbPlain',
    fileName: 'couchdb-plain',
    key: [],
  },
  {
    name: 'C++',
    componentName: 'CPlusPlusPlain',
    fileName: 'cplusplus-plain',
    key: [],
  },
  {
    name: 'crystal',
    componentName: 'CrystalOriginal',
    fileName: 'crystal-original',
    key: [],
  },
  {
    name: 'C#',
    componentName: 'CSharpPlain',
    fileName: 'csharp-plain',
    key: [],
  },
  {
    name: 'css3',
    componentName: 'CSS3Plain',
    fileName: 'css3-plain',
    key: [],
  },
  {
    name: 'cucumber',
    componentName: 'CucumberPlain',
    fileName: 'cucumber-plain',
    key: [],
  },
  {
    name: 'd3js',
    componentName: 'D3jsPlain',
    fileName: 'd3js-plain',
    key: [],
  },
  {
    name: 'dart',
    componentName: 'DartPlain',
    fileName: 'dart-plain',
    key: [],
  },
  {
    name: 'debian',
    componentName: 'DebianPlain',
    fileName: 'debian-plain',
    key: [],
  },
  {
    name: 'denojs',
    componentName: 'DenojsOriginal',
    fileName: 'denojs-original',
    key: [],
  },
  {
    name: 'digitalocean',
    componentName: 'DigitaloceanPlain',
    fileName: 'digitalocean-plain',
    key: [],
  },
  {
    name: 'django',
    componentName: 'DjangoPlain',
    fileName: 'django-plain',
    key: [],
  },
  {
    name: 'docker',
    componentName: 'DockerPlain',
    fileName: 'docker-plain',
    key: [],
  },
  {
    name: 'doctrine',
    componentName: 'DoctrinePlain',
    fileName: 'doctrine-plain',
    key: [],
  },
  {
    name: 'dot-net',
    componentName: 'DotNetPlain',
    fileName: '',
    key: [],
  },
  {
    name: 'dotnetcore',
    componentName: 'DotnetcorePlain',
    fileName: 'dotnetcore-plain',
    key: [],
  },
  {
    name: 'drupal',
    componentName: 'DrupalPlain',
    fileName: 'drupal-plain',
    key: [],
  },
  {
    name: 'electron',
    componentName: 'ElectronOriginal',
    fileName: 'electron-original',
    key: [],
  },
  {
    name: 'eleventy',
    componentName: 'EleventyPlain',
    fileName: 'eleventy-plain',
    key: [],
  },
  {
    name: 'elixir',
    componentName: 'ElixirPlain',
    fileName: 'elixir-plain',
    key: [],
  },
  {
    name: 'elm',
    componentName: 'ElmPlain',
    fileName: 'elm-plain',
    key: [],
  },
  {
    name: 'embeddedc',
    componentName: 'EmbeddedcPlain',
    fileName: 'embeddedc-plain',
    key: [],
  },
  {
    name: 'ember',
    componentName: 'EmberOriginalWordmark',
    fileName: 'ember-original-wordmark',
    key: [],
  },
  {
    name: 'erlang',
    componentName: 'ErlangPlain',
    fileName: 'erlang-plain',
    key: [],
  },
  {
    name: 'express',
    componentName: 'ExpressOriginal',
    fileName: 'express-original',
    key: [],
  },
  {
    name: 'facebook',
    componentName: 'FacebookPlain',
    fileName: 'facebook-plain',
    key: [],
  },
  {
    name: 'feathersjs',
    componentName: 'FeathersjsOriginal',
    fileName: 'feathersjs-original',
    key: [],
  },
  {
    name: 'figma',
    componentName: 'FigmaPlain',
    fileName: 'figma-plain',
    key: [],
  },
  {
    name: 'filezilla',
    componentName: 'FilezillaPlain',
    fileName: 'filezilla-plain',
    key: [],
  },
  {
    name: 'firebase',
    componentName: 'FirebasePlain',
    fileName: 'firebase-plain',
    key: [],
  },
  {
    name: 'firefox',
    componentName: 'FirefoxPlain',
    fileName: 'firefox-plain',
    key: [],
  },
  {
    name: 'flask',
    componentName: 'FlaskOriginal',
    fileName: 'flask-original',
    key: [],
  },
  {
    name: 'flutter',
    componentName: 'FlutterPlain',
    fileName: 'flutter-plain',
    key: [],
  },
  {
    name: 'foundation',
    componentName: 'FoundationPlain',
    fileName: 'foundation-plain',
    key: [],
  },
  {
    name: 'fsharp',
    componentName: 'FSharpPlain',
    fileName: 'fsharp-plain',
    key: [],
  },
  {
    name: 'gatling',
    componentName: 'GatlingPlain',
    fileName: 'gatling-plain',
    key: [],
  },
  {
    name: 'gatsby',
    componentName: 'GatsbyPlain',
    fileName: 'gatsby-plain',
    key: [],
  },
  {
    name: 'gcc',
    componentName: 'GCCPlain',
    fileName: 'gcc-plain',
    key: [],
  },
  {
    name: 'gimp',
    componentName: 'GIMPPlain',
    fileName: 'gimp-plain',
    key: [],
  },
  {
    name: 'git',
    componentName: 'GitPlain',
    fileName: 'git-plain',
    key: [],
  },
  {
    name: 'github',
    componentName: 'GitHubOriginal',
    fileName: 'github-original',
    key: [],
  },
  {
    name: 'gitlab',
    componentName: 'GitLabPlain',
    fileName: 'gitlab-plain',
    key: [],
  },
  {
    name: 'gitter',
    componentName: 'GitterPlain',
    fileName: 'gitter-plain',
    key: [],
  },
  {
    name: 'Go',
    componentName: 'GoPlain',
    fileName: 'go-plain',
    key: [],
  },
  {
    name: 'godot',
    componentName: 'GodotPlain',
    fileName: 'godot-plain',
    key: [],
  },
  {
    name: 'google',
    componentName: 'GooglePlain',
    fileName: 'google-plain',
    key: [],
  },
  {
    name: 'googlecloud',
    componentName: 'GoogleCloudPlain',
    fileName: 'googlecloud-plain',
    key: [],
  },
  {
    name: 'gradle',
    componentName: 'GradlePlain',
    fileName: 'gradle-plain',
    key: [],
  },
  {
    name: 'grails',
    componentName: 'GrailsPlain',
    fileName: 'grails-plain',
    key: [],
  },
  {
    name: 'graphql',
    componentName: 'GraphqlPlain',
    fileName: 'graphql-plain',
    key: [],
  },
  {
    name: 'groovy',
    componentName: 'GroovyPlain',
    fileName: 'groovy-plain',
    key: [],
  },
  {
    name: 'grunt',
    componentName: 'GruntPlain',
    fileName: 'grunt-plain',
    key: [],
  },
  {
    name: 'gulp',
    componentName: 'GulpPlain',
    fileName: 'gulp-plain',
    key: [],
  },
  {
    name: 'handlebars',
    componentName: 'HandlebarsOriginal',
    fileName: 'handlebars-original',
    key: [],
  },
  {
    name: 'haskell',
    componentName: 'HaskellPlain',
    fileName: 'haskell-plain',
    key: [],
  },
  {
    name: 'haxe',
    componentName: 'HaxePlain',
    fileName: 'haxe-plain',
    key: [],
  },
  {
    name: 'heroku',
    componentName: 'HerokuPlain',
    fileName: 'heroku-plain',
    key: [],
  },
  {
    name: 'html5',
    componentName: 'HTML5Plain',
    fileName: 'html5-plain',
    key: [],
  },
  {
    name: 'ie10',
    componentName: 'IE10Original',
    fileName: 'ie10-original',
    key: [],
  },
  {
    name: 'illustrator',
    componentName: 'IllustratorPlain',
    fileName: 'illustrator-plain',
    key: [],
  },
  {
    name: 'inkscape',
    componentName: 'InkscapePlain',
    fileName: 'inkscape-plain',
    key: [],
  },
  {
    name: 'intellij',
    componentName: 'IntellijPlain',
    fileName: 'intellij-plain',
    key: [],
  },
  {
    name: 'ionic',
    componentName: 'IonicOriginal',
    fileName: 'ionic-original',
    key: [],
  },
  {
    name: 'jamstack',
    componentName: 'JamstackOriginal',
    fileName: 'jamstack-original',
    key: [],
  },
  {
    name: 'jasmine',
    componentName: 'JasminePlain',
    fileName: 'jasmine-plain',
    key: [],
  },
  {
    name: 'java',
    componentName: 'JavaPlain',
    fileName: 'java-plain',
    key: [],
  },
  {
    name: 'javascript',
    componentName: 'JavascriptPlain',
    fileName: 'javascript-plain',
    key: [],
  },
  {
    name: 'jeet',
    componentName: 'JeetPlain',
    fileName: 'jeet-plain',
    key: [],
  },
  {
    name: 'jenkins',
    componentName: 'JenkinsPlain',
    fileName: 'jenkins-plain',
    key: [],
  },
  {
    name: 'jest',
    componentName: 'JestPlain',
    fileName: 'jest-plain',
    key: [],
  },
  {
    name: 'jetbrains',
    componentName: 'JetbrainsPlain',
    fileName: 'jetbrains-plain',
    key: [],
  },
  {
    name: 'jira',
    componentName: 'JiraPlain',
    fileName: 'jira-plain',
    key: [],
  },
  {
    name: 'jquery',
    componentName: 'JQueryPlain',
    fileName: 'jquery-plain',
    key: [],
  },
  {
    name: 'julia',
    componentName: 'JuliaPlain',
    fileName: 'julia-plain',
    key: [],
  },
  {
    name: 'jupyter',
    componentName: 'JupyterPlain',
    fileName: 'jupyter-plain',
    key: [],
  },
  {
    name: 'karma',
    componentName: 'KarmaPlain',
    fileName: 'karma-plain',
    key: [],
  },
  {
    name: 'knockout',
    componentName: 'KnockoutPlainWordmark',
    fileName: 'knockout-plain-wordmark',
    key: [],
  },
  {
    name: 'kotlin',
    componentName: 'KotlinPlain',
    fileName: 'kotlin-plain',
    key: [],
  },
  {
    name: 'krakenjs',
    componentName: 'KrakenjsPlain',
    fileName: 'krakenjs-plain',
    key: [],
  },
  {
    name: 'kubernetes',
    componentName: 'KubernetesPlain',
    fileName: 'kubernetes-plain',
    key: [],
  },
  {
    name: 'Labview',
    componentName: 'LabviewPlain',
    fileName: 'labview-plain',
    key: [],
  },
  {
    name: 'laravel',
    componentName: 'LaravelPlain',
    fileName: 'laravel-plain',
    key: [],
  },
  {
    name: 'less',
    componentName: 'LESSPlainWordmark',
    fileName: 'less-plain-wordmark',
    key: [],
  },
  {
    name: 'linkedin',
    componentName: 'LinkedinPlain',
    fileName: 'linkedin-plain',
    key: [],
  },
  {
    name: 'linux',
    componentName: 'LinuxPlain',
    fileName: 'linux-plain',
    key: [],
  },
  {
    name: 'lua',
    componentName: 'LuaPlain',
    fileName: 'lua-plain',
    key: [],
  },
  {
    name: 'magento',
    componentName: 'MagentoOriginal',
    fileName: 'magento-original',
    key: [],
  },
  {
    name: 'markdown',
    componentName: 'MarkdownOriginal',
    fileName: 'markdown-original',
    key: [],
  },
  {
    name: 'materialui',
    componentName: 'MaterialUIPlain',
    fileName: 'materialui-plain',
    key: [],
  },
  {
    name: 'matlab',
    componentName: 'MatlabPlain',
    fileName: 'matlab-plain',
    key: [],
  },
  {
    name: 'meteor',
    componentName: 'MeteorPlain',
    fileName: 'meteor-plain',
    key: [],
  },
  {
    name: 'minitab',
    componentName: 'MinitabPlain',
    fileName: 'minitab-plain',
    key: [],
  },
  {
    name: 'mocha',
    componentName: 'MochaPlain',
    fileName: 'mocha-plain',
    key: [],
  },
  {
    name: 'modx',
    componentName: 'ModxPlain',
    fileName: 'modx-plain',
    key: [],
  },
  {
    name: 'mongodb',
    componentName: 'MongoDBPlain',
    fileName: 'mongodb-plain',
    key: [],
  },
  {
    name: 'moodle',
    componentName: 'MoodlePlain',
    fileName: 'moodle-plain',
    key: [],
  },
  {
    name: 'msdos',
    componentName: 'MSDosPlain',
    fileName: 'msdos-plain',
    key: [],
  },
  {
    name: 'mysql',
    componentName: 'MySQLPlain',
    fileName: 'mysql-plain',
    key: [],
  },
  {
    name: 'neo4j',
    componentName: 'Neo4jPlain',
    fileName: 'neo4j-plain',
    key: [],
  },
  {
    name: 'nestjs',
    componentName: 'NestJSPlain',
    fileName: 'nestjs-plain',
    key: [],
  },
  {
    name: 'nextjs',
    componentName: 'NextJSOriginal',
    fileName: 'nextjs-original',
    key: [],
  },
  {
    name: 'nginx',
    componentName: 'NginxOriginal',
    fileName: 'nginx-original',
    key: [],
  },
  {
    name: 'nixos',
    componentName: 'NixosPlain',
    fileName: 'nixos-plain',
    key: [],
  },
  {
    name: 'nodejs',
    componentName: 'NodeJSPlain',
    fileName: 'nodejs-plain',
    key: [],
  },
  {
    name: 'nodewebkit',
    componentName: 'NodewebkitPlain',
    fileName: 'nodewebkit-plain',
    key: [],
  },
  {
    name: 'npm',
    componentName: 'NPMOriginalWordmark',
    fileName: 'npm-original-wordmark',
    key: [],
  },
  {
    name: 'numpy',
    componentName: 'NumpyPlain',
    fileName: 'numpy-plain',
    key: [],
  },
  {
    name: 'nuxtjs',
    componentName: 'NuxtJSPlain',
    fileName: 'nuxtjs-plain',
    key: [],
  },
  {
    name: 'objectivec',
    componentName: 'ObjectivecPlain',
    fileName: 'objectivec-plain',
    key: [],
  },
  {
    name: 'ocaml',
    componentName: 'OcamlPlain',
    fileName: 'ocaml-plain',
    key: [],
  },
  {
    name: 'opengl',
    componentName: 'OpenGLPlain',
    fileName: 'opengl-plain',
    key: [],
  },
  {
    name: 'opera',
    componentName: 'OperaPlain',
    fileName: 'opera-plain',
    key: [],
  },
  {
    name: 'oracle',
    componentName: 'OracleOriginal',
    fileName: 'oracle-original',
    key: [],
  },
  {
    name: 'pandas',
    componentName: 'PandasPlain',
    fileName: 'pandas-plain',
    key: [],
  },
  {
    name: 'Perl',
    componentName: 'PerlPlain',
    fileName: 'perl-plain',
    key: [],
  },
  {
    name: 'phalcon',
    componentName: 'PhalconPlain',
    fileName: 'phalcon-plain',
    key: [],
  },
  {
    name: 'Phoenix',
    componentName: 'PhoenixPlain',
    fileName: 'phoenix-plain',
    key: [],
  },
  {
    name: 'photoshop',
    componentName: 'PhotoshopPlain',
    fileName: 'photoshop-plain',
    key: [],
  },
  {
    name: 'php',
    componentName: 'PHPPlain',
    fileName: 'php-plain',
    key: [],
  },
  {
    name: 'phpstorm',
    componentName: 'PHPStormPlain',
    fileName: 'phpstorm-plain',
    key: [],
  },
  {
    name: 'postgresql',
    componentName: 'PostgreSQLPlain',
    fileName: 'postgresql-plain',
    key: [],
  },
  {
    name: 'premierepro',
    componentName: 'PremiereProPlain',
    fileName: 'premierepro-plain',
    key: [],
  },
  {
    name: 'processing',
    componentName: 'ProcessingPlain',
    fileName: 'processing-plain',
    key: [],
  },
  {
    name: 'protractor',
    componentName: 'ProtractorPlain',
    fileName: 'protractor-plain',
    key: [],
  },
  {
    name: 'putty',
    componentName: 'PuttyPlain',
    fileName: 'putty-plain',
    key: [],
  },
  {
    name: 'pycharm',
    componentName: 'PycharmPlain',
    fileName: 'pycharm-plain',
    key: [],
  },
  {
    name: 'python',
    componentName: 'PythonPlain',
    fileName: 'python-plain',
    key: [],
  },
  {
    name: 'qt',
    componentName: 'QtOriginal',
    fileName: 'qt-original',
    key: [],
  },
  {
    name: 'Dev Icons React',
    componentName: 'DeviconsReactOriginal',
    fileName: 'deviconsreact-original',
    key: [],
  },
  {
    name: 'microsoftsqlserver',
    componentName: 'MicrosoftsqlserverPlain',
    fileName: 'microsoftsqlserver-plain',
    key: [],
  },
  {
    name: 'R',
    componentName: 'RPlain',
    fileName: 'r-plain',
    key: [],
  },
  {
    name: 'rails',
    componentName: 'RailsPlain',
    fileName: 'rails-plain',
    key: [],
  },
  {
    name: 'raspberrypi',
    componentName: 'RaspberrypiLine',
    fileName: 'raspberrypi-line',
    key: [],
  },
  {
    name: 'react',
    componentName: 'ReactOriginal',
    fileName: 'react-original',
    key: [],
  },
  {
    name: 'redhat',
    componentName: 'RedhatPlain',
    fileName: 'redhat-plain',
    key: [],
  },
  {
    name: 'redis',
    componentName: 'RedisPlain',
    fileName: 'redis-plain',
    key: [],
  },
  {
    name: 'redux',
    componentName: 'ReduxOriginal',
    fileName: 'redux-original',
    key: [],
  },
  {
    name: 'rocksdb',
    componentName: 'RocksDBPlain',
    fileName: 'rocksdb-plain',
    key: [],
  },
  {
    name: 'rstudio',
    componentName: 'RstudioPlain',
    fileName: 'rstudio-plain',
    key: [],
  },
  {
    name: 'ruby',
    componentName: 'RubyPlain',
    fileName: 'ruby-plain',
    key: [],
  },
  {
    name: 'rubymine',
    componentName: 'RubyMinePlain',
    fileName: 'rubymine-plain',
    key: [],
  },
  {
    name: 'rust',
    componentName: 'RustPlain',
    fileName: 'rust-plain',
    key: [],
  },
  {
    name: 'safari',
    componentName: 'SafariPlain',
    fileName: 'safari-plain',
    key: [],
  },
  {
    name: 'salesforce',
    componentName: 'SalesforcePlain',
    fileName: 'salesforce-plain',
    key: [],
  },
  {
    name: 'sass',
    componentName: 'SASSOriginal',
    fileName: 'sass-original',
    key: [],
  },
  {
    name: 'scala',
    componentName: 'ScalaPlain',
    fileName: 'scala-plain',
    key: [],
  },
  {
    name: 'sequelize',
    componentName: 'SequelizePlain',
    fileName: 'sequelize-plain',
    key: [],
  },
  {
    name: 'shopware',
    componentName: 'ShopwareOriginal',
    fileName: 'shopware-original',
    key: [],
  },
  {
    name: 'sketch',
    componentName: 'SketchLine',
    fileName: 'sketch-line',
    key: [],
  },
  {
    name: 'slack',
    componentName: 'SlackPlain',
    fileName: 'slack-plain',
    key: [],
  },
  {
    name: 'socketio',
    componentName: 'SocketioOriginal',
    fileName: 'socketio-original',
    key: [],
  },
  {
    name: 'sourcetree',
    componentName: 'SourcetreeOriginal',
    fileName: 'sourcetree-original',
    key: [],
  },
  {
    name: 'spring',
    componentName: 'SpringPlain',
    fileName: 'spring-plain',
    key: [],
  },
  {
    name: 'spss',
    componentName: 'SpssPlain',
    fileName: 'spss-plain',
    key: [],
  },
  {
    name: 'sqlalchemy',
    componentName: 'SQLAlchemyPlain',
    fileName: 'sqlalchemy-plain',
    key: [],
  },
  {
    name: 'ssh',
    componentName: 'SSHOriginal',
    fileName: 'ssh-original',
    key: [],
  },
  {
    name: 'storybook',
    componentName: 'StorybookPlain',
    fileName: 'storybook-plain',
    key: [],
  },
  {
    name: 'stylus',
    componentName: 'StylusOriginal',
    fileName: 'stylus-original',
    key: [],
  },
  {
    name: 'subversion',
    componentName: 'SubversionOriginal',
    fileName: 'subversion-original',
    key: [],
  },
  {
    name: 'svelte',
    componentName: 'SveltePlain',
    fileName: 'svelte-plain',
    key: [],
  },
  {
    name: 'swift',
    componentName: 'SwiftPlain',
    fileName: 'swift-plain',
    key: [],
  },
  {
    name: 'symfony',
    componentName: 'SymfonyOriginal',
    fileName: 'symfony-original',
    key: [],
  },
  {
    name: 'tailwindcss',
    componentName: 'TailwindCSSPlain',
    fileName: 'tailwindcss-plain',
    key: [],
  },
  {
    name: 'tensorflow',
    componentName: 'TensorflowPlain',
    fileName: 'tensorflow-plain',
    key: [],
  },
  {
    name: 'thealgorithms',
    componentName: 'ThealgorithmsPlain',
    fileName: 'thealgorithms-plain',
    key: [],
  },
  {
    name: 'threejs',
    componentName: 'ThreeJSOriginal',
    fileName: 'threejs-original',
    key: [],
  },
  {
    name: 'tomcat',
    componentName: 'TomcatLine',
    fileName: 'tomcat-line',
    key: [],
  },
  {
    name: 'tortoisegit',
    componentName: 'TortoisegitPlain',
    fileName: 'tortoisegit-plain',
    key: [],
  },
  {
    name: 'towergit',
    componentName: 'TowergitPlain',
    fileName: 'towergit-plain',
    key: [],
  },
  {
    name: 'travis',
    componentName: 'TravisPlain',
    fileName: 'travis-plain',
    key: [],
  },
  {
    name: 'trello',
    componentName: 'TrelloPlain',
    fileName: 'trello-plain',
    key: [],
  },
  {
    name: 'twitter',
    componentName: 'TwitterOriginal',
    fileName: 'twitter-original',
    key: [],
  },
  {
    name: 'typescript',
    componentName: 'TypeScriptPlain',
    fileName: 'typescript-plain',
    key: [],
  },
  {
    name: 'typo3',
    componentName: 'Typo3Plain',
    fileName: 'typo3-plain',
    key: [],
  },
  {
    name: 'ubuntu',
    componentName: 'UbuntuPlain',
    fileName: 'ubuntu-plain',
    key: [],
  },
  {
    name: 'unity',
    componentName: 'UnityOriginal',
    fileName: 'unity-original',
    key: [],
  },
  {
    name: 'unix',
    componentName: 'UnixOriginal',
    fileName: 'unix-original',
    key: [],
  },
  {
    name: 'uwsgi',
    componentName: 'UwsgiPlain',
    fileName: 'uwsgi-plain',
    key: [],
  },
  {
    name: 'vagrant',
    componentName: 'VagrantPlain',
    fileName: 'vagrant-plain',
    key: [],
  },
  {
    name: 'vim',
    componentName: 'VimPlain',
    fileName: 'vim-plain',
    key: [],
  },
  {
    name: 'visualstudio',
    componentName: 'VisualStudioPlain',
    fileName: 'visualstudio-plain',
    key: [],
  },
  {
    name: 'vscode',
    componentName: 'VSCodePlain',
    fileName: 'vscode-plain',
    key: [],
  },
  {
    name: 'vuejs',
    componentName: 'VueJSPlain',
    fileName: 'vuejs-plain',
    key: [],
  },
  {
    name: 'vuestorefront',
    componentName: 'VuestorefrontPlain',
    fileName: 'vuestorefront-plain',
    key: [],
  },
  {
    name: 'weblate',
    componentName: 'WeblatePlain',
    fileName: 'weblate-plain',
    key: [],
  },
  {
    name: 'webpack',
    componentName: 'WebPackPlain',
    fileName: 'webpack-plain',
    key: [],
  },
  {
    name: 'webstorm',
    componentName: 'WebStormPlain',
    fileName: 'webstorm-plain',
    key: [],
  },
  {
    name: 'windows8',
    componentName: 'Windows8Original',
    fileName: 'windows8-original',
    key: [],
  },
  {
    name: 'woocommerce',
    componentName: 'WooCommercePlain',
    fileName: 'woocommerce-plain',
    key: [],
  },
  {
    name: 'wordpress',
    componentName: 'WordPressPlain',
    fileName: 'wordpress-plain',
    key: [],
  },
  {
    name: 'xd',
    componentName: 'XDPlain',
    fileName: 'xd-plain',
    key: [],
  },
  {
    name: 'yarn',
    componentName: 'YarnOriginal',
    fileName: 'yarn-original',
    key: [],
  },
  {
    name: 'yii',
    componentName: 'YiiPlain',
    fileName: 'yii-plain',
    key: [],
  },
  {
    name: 'yunohost',
    componentName: 'YunohostPlain',
    fileName: 'yunohost-plain',
    key: [],
  },
  {
    name: 'zend',
    componentName: 'ZendPlain',
    fileName: 'zend-plain',
    key: [],
  },
  {
    name: 'zig',
    componentName: 'ZigOriginal',
    fileName: 'zig-original',
    key: [],
  },
]

initialItems.sort((a, b) => {
  return a.name.localeCompare(b.name)
})

export default initialItems
